GET http://localhost:3002/products

####
GET http://localhost:3002/products/1


#### POST
POST http://localhost:3002/products
Content-Type: application/json

{
    "name": "Product 1",
    "price": 100
}

#### PUT
PUT http://localhost:3002/products/2
Content-Type: application/json

{
    "name": "Product 3",
    "price": 100
}

#### DELETE
DELETE http://localhost:3002/products/1
